### ISSUE TITLE
Incorrect values for the appsody deployment file

### ISSUE THREAD

**Issue by oiricaud** [ibm-garage-ref-storefront/storefront-ui#13]
We have https://github.com/ibm-garage-ref-storefront/storefront-ui/blob/78b9c96ff2230e71a6974accd208c4f0414a44f5/app-deploy.yaml#L67

```yaml
  name: web
  namespace: storefront-dev
```
needs to be changed to
```yaml
  name: storefront-ui
  namespace: storefront
```

**Comment by phemankita** [comment]
Current intended namespace is `storefront-dev`. That is the reason why the the name is pointing to storefront-dev. Instead of deploying to storefront use `storefront-dev` as the project namespace.
