### ISSUE TITLE
Npm "Port already in use"

### ISSUE THREAD

**Issue by hkang92** [ibm-garage-ref-storefront/storefront-ui#17]
`> node ./bin/www

Port 3000 is already in use
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bluecompute-web@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the bluecompute-web@0.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.`

**Comment by oiricaud** [comment]
This issue is related to the user's environment and is not a problem with the source code.
